# Generated by Django 4.1.3 on 2022-11-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(default='NA', max_length=255),
            preserve_default=False,
        ),
    ]
